# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5d1ed4003775026721c106571ded183e5a05126535fec893878e4deaeb31f7306f3380517d92ab6c94e582ab7f80beb48f5a54d5bf5d342fc5e4e397ecf68908

test:
  secret_key_base: 7ad76fc68442178d5d7cacefd1f063a285b61da262a93f8fd4fb56e2b0cb91dd50ba6deeed54cf5d92d936eb2d84189656cf2d87c9b79837aa36a41108c1ee75

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
